import type { ErpAdapter, ErpPermission, ErpProviderName, ErpWriteAction } from './adapter';

const emptyCaps = {
  supportsProductSearch: false,
  supportsCustomerLookup: false,
  supportsQuoteCreation: false,
  supportsOrderConfirmation: false,
  supportsInvoiceCreation: false,
  supportsDailyReport: false,
};

export const createUnimplementedAdapter = (name: ErpProviderName): ErpAdapter => ({
  name,
  capabilities: emptyCaps,
  searchProducts: async () => [],
  listServices: async () => [],
  lookupService: async () => null,
  createService: async () => null,
  updateService: async () => null,
  deleteService: async () => false,
  lookupCustomer: async () => null,
  createCustomer: async () => null,
  updateCustomer: async () => null,
  deleteCustomer: async () => false,
  createQuotation: async () => null,
  confirmOrder: async () => false,
  createInvoice: async () => false,
  addQuoteLine: async () => false,
  editQuoteLine: async () => false,
  removeQuoteLine: async () => false,
  cancelQuote: async () => false,
  sendQuotationEmail: async () => false,
  getOrderStatus: async () => null,
  getDeliveryStatus: async () => null,
  getDailySnapshot: async () => [],
  getDailySummary: async () => null,
  lookupProduct: async () => null,
  lookupCustomerByName: async () => null,
  findPaymentTermId: async () => null,
  getOrderLinks: async () => ({}),
  permissionFor: (_action: ErpWriteAction): ErpPermission => ({ role: 'admin', channel: 'ops' }),
  postPartnerNote: async () => false,
  listQuotations: async () => [],
  assignQuotationSalesperson: async () => false,
  describePartnerPrivileges: async () => ({ configured: false, groups: [] }),
  describeSignatureStatus: async () => ({ ok: false, message: `${name} ERP is not implemented.` }),
  describePaymentStatus: async () => ({ ok: false, message: `${name} ERP is not implemented.` }),
});
